// <auto-generated />
using System;
using Com.Enes.B2B.Crm.Infrastructure;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Com.Enes.B2B.Crm.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250106004012_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS_SC_UTF8")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Com.Enes.B2B.Crm.Domain.Contacts.Contact", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("ComputedHash")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Lead")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("Com.Enes.B2B.Crm.Domain.Events.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("ComputedHash")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime>("EventAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Com.Enes.B2B.Crm.Domain.Leads.Lead", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("ComputedHash")
                        .HasColumnType("NVARCHAR(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("Com.Enes.B2B.Crm.Domain.Messages.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("ComputedHash")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime>("EventAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Com.Enes.B2B.Crm.Domain.Pipelines.Pipeline", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("ComputedHash")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Pipelines", (string)null);
                });

            modelBuilder.Entity("Com.Enes.B2B.Crm.Domain.Tasks.CTask", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("ComputedHash")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Com.Enes.B2B.Crm.Domain.Tasks.TaskTypes.TaskType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ComputedHash")
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<long?>("IconId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("TaskTypes", (string)null);
                });

            modelBuilder.Entity("Com.Enes.B2B.Crm.Domain.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("ComputedHash")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
